### ISSUE TITLE
pgcheck user fixed to "pgc" in template

### ISSUE THREAD

**Issue by krisavi** [gplv2/haproxy-postgresql#3]
https://github.com/gplv2/haproxy-postgresql/blob/0114990d14a9be962f1f8dedb9bb034c0274fb17/template/standby.template#L99

It calculates the length of the user string, but not replacing the send-binary data.
I replaced it with:

`    tcp-check send-binary <%= @bn.checkuserhex %>                 # "<%= @bn.checkuser %>"                 (  <%= @bn.checkuserlen %> bytes )`

and added 

`        "<%= @bn.checkuserhex %>": checkuser.encode("utf-8").hex() + "00",`

after https://github.com/gplv2/haproxy-postgresql/blob/0114990d14a9be962f1f8dedb9bb034c0274fb17/create_haproxy_check.py#L114

**Comment by gplv2** [comment]
Hi sorry I haven't noticed this issue earlier,  I'll test and update the code, feel free to clone/patch/pull request it next time . I fixed it in 7a9a1e755b6a24db2689b7af95f6937968d9d307

**Comment by gplv2** [comment]
Thanks !
